# Welcome to Jekyll!
# General settings

minimal_mistakes_skin: "air"

# Site settings
locale: "en-US"
title: "Alexander Pries - Researcher and Data Scientist"
title_separator: "-"
subtitle: "Researcher in Social Sciences | Data Scientist & Survey Methodologist"
name: "Alexander Pries"
description: "Welcome to my personal website and blog—a space where professional expertise meets personal reflection. ..."
url: "https://alexanderpries.github.io"
baseurl: ""
repository: "AlexanderPries/alexanderpries.github.io"
teaser: "/assets/images/teaser.png"
logo: "/assets/images/icon.png"
masthead_title: ""
breadcrumbs: true
words_per_minute: 200
enable_copy_code_button: true
copyright: "Alexander Pries"
comments:
  provider: false

# Search
search: true
search_full_content: false
search_provider: lunr
lunr:
  search_within_pages: true

# Social sharing
social:
  type: "Person"
  name: "Alexander Pries"
  links:
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/alexander-pries-071639279/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/alexander_prs"
    - label: "BlueSky"
      icon: "fas fa-fw fa-link"
      url: "https://bsky.app/profile/alexprs.bsky.social"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/alexprs23/"

# Author details
author:
  name: "Alexander Pries"
  avatar: "/assets/images/bio_picture.jpg"
  bio: "Researcher & Data Scientist | Social Sciences, Social Psychology, Big Data and Survey insights"
  location: "Im echten Norden"
  email: "mailto:alexanderpries@web.de"
  links:
    - label: "email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:alexanderpries@web.de"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/alexander-pries-071639279/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/alexander_prs"
    - label: "BlueSky"
      icon: "fas fa-fw fa-link"
      url: "https://bsky.app/profile/alexprs.bsky.social"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/alexprs23/"

# Footer
footer:
  links:
    - label: "email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:alexanderpries@web.de"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/alexander-pries-071639279/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/alexander_prs"
    - label: "BlueSky"
      icon: "fas fa-fw fa-link"
      url: "https://bsky.app/profile/alexprs.bsky.social"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/alexprs23/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true