# Welcome to Jekyll!
# General settings

minimal_mistakes_skin: "my-custom-skin"

# Site settings
locale: "en-US"
title: ""
title_separator: ""
subtitle: ""
name: ""
description: ""
url: "https://alexanderpries.github.io"
baseurl: ""
repository: "AlexanderPries/alexanderpries.github.io"
teaser: ""
logo: ""
masthead_title: ""
breadcrumbs: true
words_per_minute: 200
enable_copy_code_button: true
copyright: "Alexander Pries"
comments:
  provider: false

# Search
search: true
search_full_content: false
search_provider: lunr
lunr:
  search_within_pages: true

# Social sharing
social:
  type: "Person"
  name: "Alexander Pries"
  links:
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/alexander-pries-071639279/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/alexander_prs"
    - label: "BlueSky"
      icon: "fas fa-fw fa-link"
      url: "https://bsky.app/profile/alexprs.bsky.social"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/alexprs23/"

# Author details
author:
  name: "Alexander Pries"
  avatar: "/assets/images/bio_picture.jpg"
  bio: "Hi, I'm Alexander, a researcher and data scientist passionate about exploring social sciences, big data, and survey methodology."
  highlights:
    - "Specialized in data analysis and survey design."
    - "Experienced in leveraging big data for actionable insights."
    - "A keen interest in the intersection of social psychology and technology."
  location: "Northern Germany"
  email: "alexanderpries@web.de"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:alexanderpries@web.de"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alexander-pries-071639279/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://x.com/alexander_prs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AlexanderPries"

# Footer
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:alexanderpries@web.de"
    - label: "LinkedIn"
      icon: "fas fa-fw fa-link"
      url: "https://www.linkedin.com/in/alexander-pries-071639279/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/alexander_prs"
    - label: "BlueSky"
      icon: "fas fa-fw fa-link"
      url: "https://bsky.app/profile/alexprs.bsky.social"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/alexprs23/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Collections
collections:
  professional:
    output: true
    permalink: /professional/:path/
  personal:
    output: true
    permalink: /personal/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
